cloud:
  aws:
    credentials:
      access-key: AKIA2SH7LQXPJ7D7U5MZ
      secret-key: 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
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: leapsimagebucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB

twilio:
  account_sid: ACe47c40c1144c690f78982e8d814abe5d
  token: 2727852852992be1d14a9e1307a0dfb0
  from_number: +12542724507